services:
  - type: web
    name: inf0
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
